services:
  api:
    build: .
    command: npm start
    volumes:
      - .:/usr/app
    ports:
      - '3333:3333'
    depends_on:
      - postgres
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      STYLE: docker-compose
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'